/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Daniel (https://sketchfab.com/DanielAndersson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-tiehu-hunter-9912b522c566442290b7ac71a788aead
Title: Star Wars: TIE/HU Hunter
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import tieScene from "../assets/3d/tie.glb";

const Tie = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(tieScene);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="af74037d8790402e931d93bc6ef58f6dfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Pod"
                  position={[0, 0, -13.83]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Pod_Metal_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Pod_Metal_0.geometry}
                    material={materials.Metal}
                  />
                  <mesh
                    name="Pod_MetalDark_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Pod_MetalDark_0.geometry}
                    material={materials.MetalDark}
                  />
                  <mesh
                    name="Pod_MetalOrange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Pod_MetalOrange_0.geometry}
                    material={materials.MetalOrange}
                  />
                  <mesh
                    name="Pod_PolishedMetalDark_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Pod_PolishedMetalDark_0.geometry}
                    material={materials.PolishedMetalDark}
                  />
                  <mesh
                    name="Pod_DarkWindow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Pod_DarkWindow_0.geometry}
                    material={materials.DarkWindow}
                  />
                  <group name="Interior" position={[1.631, 0.676, 0]}>
                    <mesh
                      name="Interior_PolishedMetalDark_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Interior_PolishedMetalDark_0.geometry}
                      material={materials.PolishedMetalDark}
                    />
                    <mesh
                      name="Interior_BlankScreen_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Interior_BlankScreen_0.geometry}
                      material={materials.BlankScreen}
                    />
                    <group
                      name="Point"
                      position={[-1.631, -1.339, 0.03]}
                      rotation={[-3.124, 0, 0]}
                    >
                      <group name="Object_14" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="Object_15" />
                      </group>
                    </group>
                  </group>
                  <group name="Wings" position={[0, -0.138, 0]}>
                    <mesh
                      name="Wings_Metal_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Wings_Metal_0.geometry}
                      material={materials.Metal}
                    />
                    <mesh
                      name="Wings_RedEngineGlow_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Wings_RedEngineGlow_0.geometry}
                      material={materials.RedEngineGlow}
                    />
                    <group name="Cube003" position={[-2.655, -0.146, -0.105]}>
                      <mesh
                        name="Cube003_TieWIng_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube003_TieWIng_0.geometry}
                        material={materials.TieWIng}
                      />
                      <mesh
                        name="Cube003_Metal_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube003_Metal_0.geometry}
                        material={materials.Metal}
                      />
                    </group>
                    <group name="Cube001" position={[2.655, -0.146, 0.105]}>
                      <mesh
                        name="Cube001_TieWIng_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube001_TieWIng_0.geometry}
                        material={materials.TieWIng}
                      />
                      <mesh
                        name="Cube001_Metal_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube001_Metal_0.geometry}
                        material={materials.Metal}
                      />
                    </group>
                    <group name="Cube002" position={[2.655, -0.146, -0.105]}>
                      <mesh
                        name="Cube002_TieWIng_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube002_TieWIng_0.geometry}
                        material={materials.TieWIng}
                      />
                      <mesh
                        name="Cube002_Metal_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube002_Metal_0.geometry}
                        material={materials.Metal}
                      />
                    </group>
                    <group name="Cube004" position={[-2.655, -0.146, 0.105]}>
                      <mesh
                        name="Cube004_TieWIng_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube004_TieWIng_0.geometry}
                        material={materials.TieWIng}
                      />
                      <mesh
                        name="Cube004_Metal_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube004_Metal_0.geometry}
                        material={materials.Metal}
                      />
                    </group>
                  </group>
                  <group name="Empty" position={[0, -0.138, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Tie;
